# Generated by Django 5.2.4 on 2025-07-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Full Name (as per IC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='identity_card_number',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name='IC/Identity Card No.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='short_name',
            field=models.CharField(blank=True, help_text="E.g. 'Ali', for display in tables/lists", max_length=64, verbose_name='Short Name'),
        ),
    ]
