# Generated by Django 5.2.1 on 2025-07-30 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_lecturer_course_lecturers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], default='morning', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('enrollment', 'date', 'session')},
        ),
    ]
