# Generated by Django 5.2.4 on 2025-07-31 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_attendance_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lecturers',
        ),
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lecturers', to='core.department'),
        ),
        migrations.CreateModel(
            name='ClassGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('year', models.PositiveIntegerField(default=2025)),
                ('classroom', models.CharField(blank=True, max_length=64, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classgroups', to='core.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classgroups', to='core.department')),
                ('lecturers', models.ManyToManyField(blank=True, related_name='classgroups', to='core.lecturer')),
            ],
        ),
        migrations.AddField(
            model_name='enrollment',
            name='class_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.classgroup'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='class_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.classgroup'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code', models.CharField(max_length=32)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.course')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lecturer',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='lecturers', to='core.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'subject', 'class_group')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
