# Generated by Django 5.2.4 on 2025-07-31 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_course_classroom_remove_course_lecturers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='relationship_to_student',
        ),
        migrations.AddField(
            model_name='parent',
            name='roles',
            field=models.CharField(blank=True, help_text="Comma-separated roles (e.g. 'father,guardian')", max_length=128),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Emergency Contact Name'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Emergency Contact Phone'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_relation',
            field=models.CharField(blank=True, max_length=64, verbose_name='Emergency Contact Relation'),
        ),
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='ic_number',
            field=models.CharField(default='Unknown', help_text='e.g. 010203145678', max_length=12, unique=True, verbose_name='Identity Card Number (NRIC)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='short_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
