# Generated by Django 5.2.4 on 2025-07-31 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_parent_relationship_to_student_parent_roles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='ic_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='short_name',
        ),
    ]
